// named.conf de dns01 (RHEL 9) — laboratorio enterprise-rhel-lab
// Zonas: lab.local (directa) y 10.10.10.in-addr.arpa (inversa).
// Recursión solo para la LAN del lab; consultas externas via forwarder 10.10.10.1
// (dnsmasq de libvirt). dnssec-validation desactivado para no depender del forwarder.
options {
	listen-on port 53 { 127.0.0.1; 10.10.10.20; };
	listen-on-v6 port 53 { none; };
	directory       "/var/named";
	dump-file       "/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	secroots-file   "/var/named/data/named.secroots";
	recursing-file  "/var/named/data/named.recursing";

	allow-query     { localhost; 10.10.10.0/24; };
	recursion yes;
	allow-recursion { localhost; 10.10.10.0/24; };
	forwarders { 10.10.10.1; };
	forward first;

	dnssec-validation no;
	managed-keys-directory "/var/named/dynamic";
	pid-file "/run/named/named.pid";
	session-keyfile "/run/named/session.key";
	include "/etc/crypto-policies/back-ends/bind.config";
};

logging {
	channel default_debug {
		file "data/named.run";
		severity dynamic;
	};
};

zone "." IN {
	type hint;
	file "named.ca";
};

zone "lab.local" IN {
	type master;
	file "lab.local.zone";
	allow-update { none; };
};

zone "10.10.10.in-addr.arpa" IN {
	type master;
	file "10.10.10.rev";
	allow-update { none; };
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
